[Tue Dec 27 05:43:13.383339 2016] [mpm_event:notice] [pid 2691:tid 139782154352512] AH00489: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Tue Dec 27 05:43:13.383423 2016] [core:notice] [pid 2691:tid 139782154352512] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 05:43:31.485399 2016] [mpm_event:notice] [pid 2691:tid 139782154352512] AH00491: caught SIGTERM, shutting down
[Tue Dec 27 05:43:32.551487 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 05:43:32.551523 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 05:43:32.551847 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 05:43:32.551864 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 06:03:07.366019 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 06:03:07.370746 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 06:03:07.370755 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 06:03:07.371255 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 06:03:07.371271 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 06:26:09.256974 2016] [wsgi:error] [pid 9278:tid 140104062596864] [client 190.17.238.235:53112] Target WSGI script not found or unable to stat: /var/www/html/flaskapp/flaskapp.wsgi
[Tue Dec 27 06:47:04.493053 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 06:47:04.544882 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 06:47:04.544900 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 06:47:04.545342 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 06:47:04.545365 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 06:48:59.309455 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 06:48:59.314088 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 06:48:59.314097 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 06:48:59.314615 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 06:48:59.314631 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 06:49:10.371127 2016] [wsgi:error] [pid 9884:tid 140104096167680] [client 190.17.238.235:53196] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 06:49:16.799676 2016] [wsgi:error] [pid 9884:tid 140104087774976] [client 190.17.238.235:53197] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 06:49:24.310011 2016] [wsgi:error] [pid 9884:tid 140104079382272] [client 190.17.238.235:53198] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 06:49:29.634930 2016] [wsgi:error] [pid 9884:tid 140104070989568] [client 190.17.238.235:53199] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 06:49:36.307081 2016] [wsgi:error] [pid 9884:tid 140104062596864] [client 190.17.238.235:53200] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 09:34:41.052225 2016] [wsgi:error] [pid 9885:tid 140104096167680] [client 187.109.54.170:43017] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 12:10:47.275137 2016] [wsgi:error] [pid 9885:tid 140104079382272] [client 175.123.98.240:61524] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 15:15:54.114047 2016] [wsgi:error] [pid 9884:tid 140103879964416] [client 190.17.238.235:49238] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 15:16:03.083769 2016] [wsgi:error] [pid 9885:tid 140104062596864] [client 190.17.238.235:49301] Target WSGI script not found or unable to stat: /var/www/html/tesis, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/login
[Tue Dec 27 15:46:34.123038 2016] [wsgi:error] [pid 9884:tid 140103863179008] [client 121.199.70.200:16971] Target WSGI script not found or unable to stat: /var/www/html/tesis
[Tue Dec 27 15:57:53.445417 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 15:57:53.498749 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 15:57:53.498765 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 15:57:53.499469 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 15:57:53.499501 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 15:58:06.030919 2016] [wsgi:error] [pid 15853:tid 140104096167680] [client 190.17.238.235:49740] Target WSGI script not found or unable to stat: /var/www/html/probando
[Tue Dec 27 15:58:06.046648 2016] [wsgi:error] [pid 15854:tid 140104096167680] [client 190.17.238.235:49741] Target WSGI script not found or unable to stat: /var/www/html/probando
[Tue Dec 27 15:58:12.785967 2016] [wsgi:error] [pid 15854:tid 140104087774976] [client 190.17.238.235:49744] Target WSGI script not found or unable to stat: /var/www/html/probando
[Tue Dec 27 16:02:50.222172 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:02:50.274216 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:02:50.274232 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:02:50.274843 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:02:50.274862 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:03:32.648862 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751] mod_wsgi (pid=15958): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:03:32.648898 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751] mod_wsgi (pid=15958): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:03:32.648924 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751] Traceback (most recent call last):
[Tue Dec 27 16:03:32.648941 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:03:32.648995 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751]     from flaskapp import app as application
[Tue Dec 27 16:03:32.649007 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:03:32.649077 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:03:32.649097 2016] [wsgi:error] [pid 15958:tid 140103972284160] [client 190.17.238.235:49751] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:03:37.622587 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753] mod_wsgi (pid=15958): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:03:37.623684 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753] mod_wsgi (pid=15958): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:03:37.623709 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753] Traceback (most recent call last):
[Tue Dec 27 16:03:37.623727 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:03:37.623753 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753]     from flaskapp import app as application
[Tue Dec 27 16:03:37.623763 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:03:37.623790 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:03:37.623806 2016] [wsgi:error] [pid 15958:tid 140103963891456] [client 190.17.238.235:49753] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:03:37.677475 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752] mod_wsgi (pid=15957): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:03:37.677520 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752] mod_wsgi (pid=15957): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:03:37.677543 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752] Traceback (most recent call last):
[Tue Dec 27 16:03:37.677560 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:03:37.677609 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752]     from flaskapp import app as application
[Tue Dec 27 16:03:37.677620 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:03:37.677673 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:03:37.677691 2016] [wsgi:error] [pid 15957:tid 140104096167680] [client 190.17.238.235:49752] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:04:00.573478 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756] mod_wsgi (pid=15957): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:04:00.573527 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756] mod_wsgi (pid=15957): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:04:00.573552 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756] Traceback (most recent call last):
[Tue Dec 27 16:04:00.573583 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:04:00.573613 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756]     from flaskapp import app as application
[Tue Dec 27 16:04:00.573630 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:04:00.573644 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:04:00.573664 2016] [wsgi:error] [pid 15957:tid 140104070989568] [client 190.17.238.235:49756] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:05:43.768722 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:05:43.820817 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:05:43.820851 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:05:43.821492 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:05:43.821512 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:06:12.222349 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760] mod_wsgi (pid=16049): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:06:12.222388 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760] mod_wsgi (pid=16049): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:06:12.222412 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760] Traceback (most recent call last):
[Tue Dec 27 16:06:12.222428 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:06:12.222489 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760]     from flaskapp import app as application
[Tue Dec 27 16:06:12.222501 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:06:12.222554 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:06:12.222573 2016] [wsgi:error] [pid 16049:tid 140103921927936] [client 190.17.238.235:49760] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:06:12.223985 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761] mod_wsgi (pid=16049): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:06:12.223998 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761] mod_wsgi (pid=16049): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:06:12.224012 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761] Traceback (most recent call last):
[Tue Dec 27 16:06:12.224028 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:06:12.224047 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761]     from flaskapp import app as application
[Tue Dec 27 16:06:12.224055 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:06:12.224068 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:06:12.224080 2016] [wsgi:error] [pid 16049:tid 140104087774976] [client 190.17.238.235:49761] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:06:22.601979 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763] mod_wsgi (pid=16049): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:06:22.602016 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763] mod_wsgi (pid=16049): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:06:22.602038 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763] Traceback (most recent call last):
[Tue Dec 27 16:06:22.602068 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:06:22.602098 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763]     from flaskapp import app as application
[Tue Dec 27 16:06:22.602106 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:06:22.602119 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:06:22.602136 2016] [wsgi:error] [pid 16049:tid 140104070989568] [client 190.17.238.235:49763] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:09:53.392683 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:09:53.444697 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:09:53.444714 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:09:53.445370 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:09:53.445390 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:10:15.664847 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784] mod_wsgi (pid=16127): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:10:15.664888 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784] mod_wsgi (pid=16127): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:10:15.664926 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784] Traceback (most recent call last):
[Tue Dec 27 16:10:15.664945 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:10:15.665009 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784]     from flaskapp import app as application
[Tue Dec 27 16:10:15.665020 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:10:15.665073 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:10:15.665104 2016] [wsgi:error] [pid 16127:tid 140104096167680] [client 190.17.238.235:49784] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:11:21.892570 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:11:21.944914 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:11:21.944932 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:11:21.945571 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:11:21.945591 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:11:30.388994 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788] mod_wsgi (pid=16200): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:11:30.389048 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788] mod_wsgi (pid=16200): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:11:30.389072 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788] Traceback (most recent call last):
[Tue Dec 27 16:11:30.389098 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:11:30.389152 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788]     from flaskapp import app as application
[Tue Dec 27 16:11:30.389163 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788]   File "/var/www/html/flaskapp/flaskapp.py", line 9, in <module>
[Tue Dec 27 16:11:30.389219 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:11:30.389238 2016] [wsgi:error] [pid 16200:tid 140104096167680] [client 190.17.238.235:49788] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:13:10.272161 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 16200 still did not exit, sending a SIGTERM
[Tue Dec 27 16:13:12.274450 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 16200 still did not exit, sending a SIGTERM
[Tue Dec 27 16:13:14.278029 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 16200 still did not exit, sending a SIGTERM
[Tue Dec 27 16:13:16.280322 2016] [core:error] [pid 3515:tid 140104196171648] AH00046: child process 16200 still did not exit, sending a SIGKILL
[Tue Dec 27 16:13:17.281503 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:13:17.338748 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:13:17.338761 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:13:17.339332 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:13:17.339352 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:14:37.857590 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:14:37.909746 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:14:37.909759 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:14:37.910326 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:14:37.910343 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:14:46.028029 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799] mod_wsgi (pid=16360): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:14:46.028071 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799] mod_wsgi (pid=16360): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:14:46.028093 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799] Traceback (most recent call last):
[Tue Dec 27 16:14:46.028111 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:14:46.028170 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799]     from flaskapp import app as application
[Tue Dec 27 16:14:46.028182 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799]   File "/var/www/html/flaskapp/flaskapp.py", line 7, in <module>
[Tue Dec 27 16:14:46.028214 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799]     from flask_sqlalchemy import SQLAlchemy
[Tue Dec 27 16:14:46.028236 2016] [wsgi:error] [pid 16360:tid 140104096167680] [client 190.17.238.235:49799] ImportError: No module named flask_sqlalchemy
[Tue Dec 27 16:52:02.058477 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:52:02.110774 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:52:02.110792 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:52:02.111430 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:52:02.111450 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:54:05.804473 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 16:54:05.856451 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 16:54:05.856466 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 16:54:05.857025 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 16:54:05.857042 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 16:55:36.454927 2016] [wsgi:error] [pid 16664:tid 140103980676864] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 16:55:36.454995 2016] [wsgi:error] [pid 16664:tid 140103980676864]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 16:55:36.457442 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160] mod_wsgi (pid=16664): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 16:55:36.457452 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160] mod_wsgi (pid=16664): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 16:55:36.457470 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160] Traceback (most recent call last):
[Tue Dec 27 16:55:36.457485 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 16:55:36.457521 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]     from flaskapp import app as application
[Tue Dec 27 16:55:36.457531 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]   File "/var/www/html/flaskapp/flaskapp.py", line 42, in <module>
[Tue Dec 27 16:55:36.457587 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]     perfilesDeTwitter = levantarPerfilesDeTwitter ()
[Tue Dec 27 16:55:36.457598 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]   File "/var/www/html/flaskapp/flaskapp.py", line 40, in levantarPerfilesDeTwitter
[Tue Dec 27 16:55:36.457613 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160]     return ret
[Tue Dec 27 16:55:36.457629 2016] [wsgi:error] [pid 16664:tid 140103980676864] [client 190.17.238.235:50160] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 17:00:51.245689 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:00:51.297735 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:00:51.297751 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:00:51.298404 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:00:51.298423 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:01:03.571756 2016] [wsgi:error] [pid 16757:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:01:03.571797 2016] [wsgi:error] [pid 16757:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:03:14.464760 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:03:14.516905 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:03:14.516922 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:03:14.517552 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:03:14.517571 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:03:20.432509 2016] [wsgi:error] [pid 16832:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:03:20.432552 2016] [wsgi:error] [pid 16832:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:03:20.435198 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196] mod_wsgi (pid=16832): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 17:03:20.435224 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196] mod_wsgi (pid=16832): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 17:03:20.435244 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196] Traceback (most recent call last):
[Tue Dec 27 17:03:20.435263 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 17:03:20.435324 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]     from flaskapp import app as application
[Tue Dec 27 17:03:20.435335 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]   File "/var/www/html/flaskapp/flaskapp.py", line 37, in <module>
[Tue Dec 27 17:03:20.435375 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]     perfilesDeTwitter = levantarPerfilesDeTwitter ()
[Tue Dec 27 17:03:20.435386 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]   File "/var/www/html/flaskapp/flaskapp.py", line 35, in levantarPerfilesDeTwitter
[Tue Dec 27 17:03:20.435402 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196]     return ret
[Tue Dec 27 17:03:20.435431 2016] [wsgi:error] [pid 16832:tid 140104096167680] [client 190.17.238.235:50196] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 17:04:54.412633 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:04:54.464704 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:04:54.464724 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:04:54.465286 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:04:54.465302 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:04:58.923238 2016] [wsgi:error] [pid 16910:tid 140104062596864] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:04:58.923275 2016] [wsgi:error] [pid 16910:tid 140104062596864]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:04:58.925757 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200] mod_wsgi (pid=16910): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 17:04:58.925768 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200] mod_wsgi (pid=16910): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 17:04:58.925801 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200] Traceback (most recent call last):
[Tue Dec 27 17:04:58.925817 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 17:04:58.925854 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]     from flaskapp import app as application
[Tue Dec 27 17:04:58.925865 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]   File "/var/www/html/flaskapp/flaskapp.py", line 37, in <module>
[Tue Dec 27 17:04:58.925906 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]     perfilesDeTwitter = levantarPerfilesDeTwitter ()
[Tue Dec 27 17:04:58.925917 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]   File "/var/www/html/flaskapp/flaskapp.py", line 35, in levantarPerfilesDeTwitter
[Tue Dec 27 17:04:58.925933 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200]     return ret
[Tue Dec 27 17:04:58.925962 2016] [wsgi:error] [pid 16910:tid 140104062596864] [client 190.17.238.235:50200] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 17:07:43.328748 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 16910 still did not exit, sending a SIGTERM
[Tue Dec 27 17:07:45.331021 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 16910 still did not exit, sending a SIGTERM
[Tue Dec 27 17:07:46.333404 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:07:46.385548 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:07:46.385565 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:07:46.386206 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:07:46.386225 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:07:46.591875 2016] [wsgi:error] [pid 16992:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:07:46.591917 2016] [wsgi:error] [pid 16992:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:36:35.616317 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:36:35.668335 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:36:35.668350 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:36:35.668927 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:36:35.668947 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:36:43.987514 2016] [wsgi:error] [pid 17086:tid 140103930320640] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:36:43.987555 2016] [wsgi:error] [pid 17086:tid 140103930320640]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:39:31.072589 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:39:31.124709 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:39:31.124725 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:39:31.125309 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:39:31.125326 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:39:37.229273 2016] [wsgi:error] [pid 17160:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:39:37.229314 2016] [wsgi:error] [pid 17160:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:39:37.232156 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253] mod_wsgi (pid=17160): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 17:39:37.232169 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253] mod_wsgi (pid=17160): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 17:39:37.232203 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253] Traceback (most recent call last):
[Tue Dec 27 17:39:37.232222 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 17:39:37.232262 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]     from flaskapp import app as application
[Tue Dec 27 17:39:37.232273 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]   File "/var/www/html/flaskapp/flaskapp.py", line 40, in <module>
[Tue Dec 27 17:39:37.232316 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]     clavesJsolesDeTwitter = levantarPerfilesDeTwitter ()
[Tue Dec 27 17:39:37.232327 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 17:39:37.232343 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253]     return ret
[Tue Dec 27 17:39:37.232371 2016] [wsgi:error] [pid 17160:tid 140104096167680] [client 190.17.238.235:50253] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 17:41:19.253470 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:41:19.305569 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:41:19.305585 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:41:19.306212 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:41:19.306231 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:41:22.255404 2016] [wsgi:error] [pid 17233:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:41:22.255458 2016] [wsgi:error] [pid 17233:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:41:22.258315 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264] mod_wsgi (pid=17233): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 17:41:22.258328 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264] mod_wsgi (pid=17233): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 17:41:22.258361 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264] Traceback (most recent call last):
[Tue Dec 27 17:41:22.258379 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 17:41:22.258417 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]     from flaskapp import app as application
[Tue Dec 27 17:41:22.258428 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>
[Tue Dec 27 17:41:22.258468 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]     perfilesDeTwitter = levantarPerfilesDeTwitter()
[Tue Dec 27 17:41:22.258479 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 17:41:22.258495 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264]     return ret
[Tue Dec 27 17:41:22.258512 2016] [wsgi:error] [pid 17233:tid 140104096167680] [client 190.17.238.235:50264] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 17:41:57.929761 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:41:57.981628 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:41:57.981646 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:41:57.982262 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:41:57.982280 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:42:01.848786 2016] [wsgi:error] [pid 17305:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:42:01.848841 2016] [wsgi:error] [pid 17305:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:44:13.176333 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17306 still did not exit, sending a SIGTERM
[Tue Dec 27 17:44:15.178640 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17306 still did not exit, sending a SIGTERM
[Tue Dec 27 17:44:16.179795 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:44:16.231897 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:44:16.231912 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:44:16.232536 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:44:16.232556 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:44:16.438080 2016] [wsgi:error] [pid 17390:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:44:16.438106 2016] [wsgi:error] [pid 17390:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:44:16.994566 2016] [wsgi:error] [pid 17391:tid 140104087774976] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:44:16.994605 2016] [wsgi:error] [pid 17391:tid 140104087774976]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:45:47.435063 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:45:47.487365 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:45:47.487382 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:45:47.487989 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:45:47.488006 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:45:54.989119 2016] [wsgi:error] [pid 17465:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:45:54.989175 2016] [wsgi:error] [pid 17465:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:47:09.858778 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:47:09.910979 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:47:09.910991 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:47:09.911550 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:47:09.911576 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:47:49.265565 2016] [wsgi:error] [pid 17539:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:47:49.265623 2016] [wsgi:error] [pid 17539:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:51:11.355436 2016] [wsgi:error] [pid 17540:tid 140103821215488] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:51:11.355481 2016] [wsgi:error] [pid 17540:tid 140103821215488]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:55:30.768614 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 17:55:30.820476 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 17:55:30.820490 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 17:55:30.821054 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 17:55:30.821074 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 17:55:44.378610 2016] [wsgi:error] [pid 17632:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:55:44.378653 2016] [wsgi:error] [pid 17632:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 17:55:50.943312 2016] [wsgi:error] [pid 17631:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 17:55:50.943354 2016] [wsgi:error] [pid 17631:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:02:37.599301 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663] [2016-12-27 18:02:37,596] ERROR in app: Exception on /jugarPrimeraVez [POST], referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599326 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663] Traceback (most recent call last):, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599330 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599334 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     response = self.full_dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599343 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599347 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     rv = self.handle_user_exception(e), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599350 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599353 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     reraise(exc_type, exc_value, tb), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599355 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599358 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     rv = self.dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599361 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599364 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599367 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]   File "/var/www/html/flaskapp/flaskapp.py", line 81, in jugarPrimeraVez, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599369 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663]     perfiles = preparar.obtenerPerfiles(name,dicEsclavoToPerfilesTwitterVistos,perfilesDeTwitter,dicPerfilesDeTwitterToCantidadVistos,cantPerfilesAmostrar) #perfilesDeTwitter[0:2]    #MIRAR ESTOOOOOOOOOOOOO SELECCION DE PERFILES, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:02:37.599373 2016] [wsgi:error] [pid 17632:tid 140103921927936] [client 190.17.238.235:50663] NameError: global name 'perfilesDeTwitter' is not defined, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:05:16.078439 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17632 still did not exit, sending a SIGTERM
[Tue Dec 27 18:05:18.080733 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17632 still did not exit, sending a SIGTERM
[Tue Dec 27 18:05:20.083073 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 18:05:20.135450 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 18:05:20.135468 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 18:05:20.136085 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 18:05:20.136103 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 18:05:20.340635 2016] [wsgi:error] [pid 17710:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:05:20.340672 2016] [wsgi:error] [pid 17710:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:05:20.343546 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691] mod_wsgi (pid=17710): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 18:05:20.343558 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691] mod_wsgi (pid=17710): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 18:05:20.343578 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691] Traceback (most recent call last):
[Tue Dec 27 18:05:20.343596 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 18:05:20.343650 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]     from flaskapp import app as application
[Tue Dec 27 18:05:20.343661 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>
[Tue Dec 27 18:05:20.343713 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]     perfilesDeTwitter = levantarPerfilesDeTwitter()
[Tue Dec 27 18:05:20.343723 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 18:05:20.343738 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691]     return ret
[Tue Dec 27 18:05:20.343755 2016] [wsgi:error] [pid 17710:tid 140104096167680] [client 190.17.238.235:50691] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 18:06:21.847963 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17709 still did not exit, sending a SIGTERM
[Tue Dec 27 18:06:21.848034 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17710 still did not exit, sending a SIGTERM
[Tue Dec 27 18:06:23.850306 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17709 still did not exit, sending a SIGTERM
[Tue Dec 27 18:06:23.851870 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17710 still did not exit, sending a SIGTERM
[Tue Dec 27 18:06:24.853021 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 18:06:24.905175 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 18:06:24.905190 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 18:06:24.905821 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 18:06:24.905841 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 18:06:25.110376 2016] [wsgi:error] [pid 17783:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:06:25.110427 2016] [wsgi:error] [pid 17783:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:06:26.363061 2016] [wsgi:error] [pid 17782:tid 140104087774976] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:06:26.363134 2016] [wsgi:error] [pid 17782:tid 140104087774976]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:11:38.870618 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17782 still did not exit, sending a SIGTERM
[Tue Dec 27 18:11:40.872915 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17782 still did not exit, sending a SIGTERM
[Tue Dec 27 18:11:42.875178 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 18:11:42.927498 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 18:11:42.927517 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 18:11:42.928208 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 18:11:42.928226 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 18:11:43.656087 2016] [wsgi:error] [pid 17879:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:11:43.656126 2016] [wsgi:error] [pid 17879:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:11:43.658933 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722] mod_wsgi (pid=17879): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 18:11:43.658981 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722] mod_wsgi (pid=17879): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 18:11:43.659006 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722] Traceback (most recent call last):
[Tue Dec 27 18:11:43.659026 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 18:11:43.659070 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]     from flaskapp import app as application
[Tue Dec 27 18:11:43.659082 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>
[Tue Dec 27 18:11:43.659163 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]     perfilesDeTwitter = levantarPerfilesDeTwitter()
[Tue Dec 27 18:11:43.659175 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 18:11:43.659192 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722]     return ret
[Tue Dec 27 18:11:43.659209 2016] [wsgi:error] [pid 17879:tid 140104096167680] [client 190.17.238.235:50722] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 18:12:36.526611 2016] [core:warn] [pid 3515:tid 140104196171648] AH00045: child process 17878 still did not exit, sending a SIGTERM
[Tue Dec 27 18:12:37.527845 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 18:12:37.594192 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 18:12:37.594209 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 18:12:37.594912 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 18:12:37.594964 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 18:12:37.802626 2016] [wsgi:error] [pid 17952:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:12:37.802653 2016] [wsgi:error] [pid 17952:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:12:38.867631 2016] [wsgi:error] [pid 17951:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:12:38.867670 2016] [wsgi:error] [pid 17951:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:12:52.493176 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751] [2016-12-27 18:12:52,492] ERROR in app: Exception on /jugarPrimeraVez [POST], referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493221 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751] Traceback (most recent call last):, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493225 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493228 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     response = self.full_dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493231 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493234 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     rv = self.handle_user_exception(e), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493236 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493239 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     reraise(exc_type, exc_value, tb), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493242 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493244 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     rv = self.dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493247 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493250 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493263 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]   File "/var/www/html/flaskapp/flaskapp.py", line 81, in jugarPrimeraVez, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493267 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751]     perfiles = preparar.obtenerPerfiles(name,dicEsclavoToPerfilesTwitterVistos,perfilesDeTwitter,dicPerfilesDeTwitterToCantidadVistos,cantPerfilesAmostrar) #perfilesDeTwitter[0:2]    #MIRAR ESTOOOOOOOOOOOOO SELECCION DE PERFILES, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:12:52.493270 2016] [wsgi:error] [pid 17952:tid 140103972284160] [client 190.17.238.235:50751] NameError: global name 'perfilesDeTwitter' is not defined, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250672 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785] [2016-12-27 18:13:31,250] ERROR in app: Exception on /jugarPrimeraVez [POST], referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250704 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785] Traceback (most recent call last):, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250708 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250712 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     response = self.full_dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250715 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250718 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     rv = self.handle_user_exception(e), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250720 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250723 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     reraise(exc_type, exc_value, tb), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250726 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250728 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     rv = self.dispatch_request(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250731 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250734 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     return self.view_functions[rule.endpoint](**req.view_args), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250737 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]   File "/var/www/html/flaskapp/flaskapp.py", line 81, in jugarPrimeraVez, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250749 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785]     perfiles = preparar.obtenerPerfiles(name,dicEsclavoToPerfilesTwitterVistos,perfilesDeTwitter,dicPerfilesDeTwitterToCantidadVistos,cantPerfilesAmostrar) #perfilesDeTwitter[0:2]    #MIRAR ESTOOOOOOOOOOOOO SELECCION DE PERFILES, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:13:31.250753 2016] [wsgi:error] [pid 17952:tid 140103846393600] [client 190.17.238.235:50785] NameError: global name 'perfilesDeTwitter' is not defined, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:26:38.190044 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00494: SIGHUP received.  Attempting to restart
[Tue Dec 27 18:26:38.242425 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Compiled for Python/2.7.11.
[Tue Dec 27 18:26:38.242444 2016] [wsgi:warn] [pid 3515:tid 140104196171648] mod_wsgi: Runtime using Python/2.7.12.
[Tue Dec 27 18:26:38.243144 2016] [mpm_event:notice] [pid 3515:tid 140104196171648] AH00489: Apache/2.4.18 (Ubuntu) mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Dec 27 18:26:38.243165 2016] [core:notice] [pid 3515:tid 140104196171648] AH00094: Command line: '/usr/sbin/apache2'
[Tue Dec 27 18:26:43.312430 2016] [wsgi:error] [pid 18044:tid 140104096167680] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:26:43.312472 2016] [wsgi:error] [pid 18044:tid 140104096167680]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:26:43.315121 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893] mod_wsgi (pid=18044): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 18:26:43.315132 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893] mod_wsgi (pid=18044): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 18:26:43.315150 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893] Traceback (most recent call last):
[Tue Dec 27 18:26:43.315168 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 18:26:43.315204 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]     from flaskapp import app as application
[Tue Dec 27 18:26:43.315214 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>
[Tue Dec 27 18:26:43.315266 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]     perfilesDeTwitter = levantarPerfilesDeTwitter()
[Tue Dec 27 18:26:43.315277 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 18:26:43.315292 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893]     return ret
[Tue Dec 27 18:26:43.315308 2016] [wsgi:error] [pid 18044:tid 140104096167680] [client 190.17.238.235:50893] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 18:26:54.713460 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250] mod_wsgi (pid=18044): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module.
[Tue Dec 27 18:26:54.713499 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250] mod_wsgi (pid=18044): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'.
[Tue Dec 27 18:26:54.713527 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250] Traceback (most recent call last):
[Tue Dec 27 18:26:54.713544 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>
[Tue Dec 27 18:26:54.713575 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]     from flaskapp import app as application
[Tue Dec 27 18:26:54.713584 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>
[Tue Dec 27 18:26:54.713598 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]     perfilesDeTwitter = levantarPerfilesDeTwitter()
[Tue Dec 27 18:26:54.713620 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter
[Tue Dec 27 18:26:54.713642 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250]     return ret
[Tue Dec 27 18:26:54.713658 2016] [wsgi:error] [pid 18044:tid 140104087774976] [client 173.252.88.94:46250] UnboundLocalError: local variable 'ret' referenced before assignment
[Tue Dec 27 18:27:23.295388 2016] [wsgi:error] [pid 18043:tid 140103980676864] /usr/local/lib/python2.7/dist-packages/flask_sqlalchemy/__init__.py:800: UserWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.
[Tue Dec 27 18:27:23.295433 2016] [wsgi:error] [pid 18043:tid 140103980676864]   warnings.warn('SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True to suppress this warning.')
[Tue Dec 27 18:27:23.298070 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447] mod_wsgi (pid=18043): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module., referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298083 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447] mod_wsgi (pid=18043): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'., referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298102 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447] Traceback (most recent call last):, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298121 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298159 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]     from flaskapp import app as application, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298170 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298224 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]     perfilesDeTwitter = levantarPerfilesDeTwitter(), referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298235 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298252 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447]     return ret, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.298269 2016] [wsgi:error] [pid 18043:tid 140103980676864] [client 186.148.137.177:35447] UnboundLocalError: local variable 'ret' referenced before assignment, referer: http://m.facebook.com/
[Tue Dec 27 18:27:23.663073 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448] mod_wsgi (pid=18044): Target WSGI script '/var/www/html/flaskapp/flaskapp.wsgi' cannot be loaded as Python module., referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663120 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448] mod_wsgi (pid=18044): Exception occurred processing WSGI script '/var/www/html/flaskapp/flaskapp.wsgi'., referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663148 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448] Traceback (most recent call last):, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663168 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]   File "/var/www/html/flaskapp/flaskapp.wsgi", line 4, in <module>, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663198 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]     from flaskapp import app as application, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663207 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]   File "/var/www/html/flaskapp/flaskapp.py", line 38, in <module>, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663221 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]     perfilesDeTwitter = levantarPerfilesDeTwitter(), referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663230 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]   File "/var/www/html/flaskapp/flaskapp.py", line 36, in levantarPerfilesDeTwitter, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663242 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448]     return ret, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
[Tue Dec 27 18:27:23.663257 2016] [wsgi:error] [pid 18044:tid 140104079382272] [client 186.148.137.177:35448] UnboundLocalError: local variable 'ret' referenced before assignment, referer: http://ec2-35-163-121-163.us-west-2.compute.amazonaws.com/
